package co.datainsider.license.domain.permissions

object PermissionKeys {
  final val Cdp = "CdpPermission"
  final val Lake = "LakePermission"
  final val NumUsers = "NumUsersPermission"
  final val DataCook = "DataCookPermission"
  final val Ingestion = "IngestionPermission"
  final val Streaming = "StreamingPermission"
  final val UserActivity = "UserActivityPermission"
  final val Billing = "BillingPermission"
  final val ClickhouseConfig = "ClickhouseConfigPermission"
  final val UserManagement = "UserManagementPermission"
  final val ApiKey = "ApiKeyPermission"
  final val TableRelationship = "GoogleOAuthPermission"
  final val GoogleOAuth = "GoogleOAuthPermission"
  final val LogoAndCompanyName = "LogoAndCompanyNamePermission"
  final val PrimarySupport = "PrimarySupportPermission"
  final val DashboardPassword = "DashboardPasswordPermission"
  final val MySqlIngestion = "MySqlIngestionPermission"
  final val MongoIngestion = "MongoIngestionPermission"
  final val GenericJdbcIngestion = "GenericJdbcIngestionPermission"
  final val OracleIngestion = "OracleIngestionPermission"
  final val MsSqlIngestion = "MsSqlIngestionPermission"
  final val RedshiftIngestion = "RedshiftIngestionPermission"
  final val BigQueryIngestion = "BigQueryIngestionPermission"
  final val PostgreIngestion = "PostgreIngestionPermission"
  final val GA3Ingestion = "GA3IngestionPermission"
  final val GA4Ingestion = "GA4IngestionPermission"
  final val GoogleAdsIngestion = "GoogleAdsIngestionPermission"
  final val GoogleSheetIngestion = "GoogleSheetIngestionPermission"
  final val ShopifyIngestion = "ShopifyIngestionPermission"
  final val S3Ingestion = "S3IngestionPermission"
  final val NumEditors = "NumEditorsPermission"
  final val NumViewers = "NumViewersPermission"
  final val Saas = "SaasPermission"
}
