export enum ColumnType {
  bool = 'bool',
  int8 = 'int8',
  int16 = 'int16',
  int32 = 'int32',
  int64 = 'int64',
  uint8 = 'uint8',
  uint16 = 'uint16',
  uint32 = 'uint32',
  uint64 = 'uint64',
  float = 'float',
  float64 = 'float64',
  double = 'double',
  string = 'string',
  date = 'date',
  datetime = 'datetime',
  datetime64 = 'datetime64',
  array = 'array',
  nested = 'nested'
}
