version: '3'
services:
  rocket-bi-server:
    image: datainsiderco/rocket-bi-server:main
    container_name: rocket-bi-server
    restart: always
    environment:
      MODE: production
    volumes:
      - ./conf:/app/conf
      - ./logs:/app/logs
      - biservice-mapdata:/app/mapdata

volumes:
  biservice-mapdata:
    external: true

networks:
  default:
    external:
      name: rocket_network