export enum DataSourceType {
  MySql = 'MySql',
  MSSql = 'SqlServer',
  Oracle = 'Oracle',
  Redshift = 'Redshift',
  BigQuery = 'BigQuery',
  BigQueryV2 = 'BigQueryV2',
  PostgreSql = 'Postgres',
  GA = 'Ga',
  GA4 = 'Ga4',
  GoogleSheet = 'GoogleSheet',
  GoogleAds = 'GoogleAds',
  Tiktok = 'TikTok',
  Others = 'Others',
  GenericJdbc = 'GenericJdbc',
  MongoDB = 'MongoDB',
  Unsupported = 'Unknown',
  JavaScript = 'JavaScript',
  IOS = 'IOS',
  Android = 'Android',
  ReactNative = 'ReactNative',
  Flutter = 'Flutter',
  Shopify = 'Shopify',
  S3 = 'S3',
  Facebook = 'Facebook',
  Palexy = 'Palexy',
  GoogleSearchConsole = 'GoogleSearchConsole'
}
