version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: rocket-bi-mysql
    command: mysqld --user=root --verbose
    ports:
      - 3306:3306
    volumes:
      - /var/lib/rocket-bi/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: "di"
      MYSQL_PASSWORD: "di@2020!"
      MYSQL_ROOT_PASSWORD: "di@2020!"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: always

  ssdb:
    image: wendal/ssdb:latest
    container_name: rocket-bi-ssdb
    ports:
      - 8888:8888
    volumes:
      - /var/lib/rocket-bi/ssdb:/var/lib/ssdb/data
    restart: always

  rocket-bi-server:
    image: datainsiderco/rocket-bi-server:latest
    container_name: rocket-bi-server
    ports:
      - 8080:8080
    volumes:
      - /var/lib/rocket-bi/server/logs:/app/logs
    environment:
      MODE: production
    restart: always
  
  rocket-bi-web:
    image: datainsiderco/rocket-bi-web:latest
    container_name: rocket-bi-web
    restart: always
    ports:
      - 5050:8080
