local.doc.root = "./src/main/resources"
profiler_path_prefix = ""

server {
  http {
    port = ":8489"
  }
  thrift {
    port = ":8487"
  }
  admin {
    disable = true
  }
}

admin_secret_key = "12345678"
service_key = 12345678


db {


  ssdb {
    host = "ssdb"
    port = 8888
    timeout_in_ms = 60000
  }

  clickhouse {
    driver_class = "com.github.housepower.jdbc.ClickHouseDriver"
    url = "jdbc:clickhouse://clickhouse_server_di:9000"
    user = "default"
    password = ""
  }
}


caas {
  thrift {
    host = "user_profile"
    port = "8589"
    timeout_sec = 5
    client_id = "caas-client-from-ingestion-service"
  }
}