server {
  http {
    port = ":8080"
  }
  thrift {
    port = ":8084"
  }
  admin {
    disable = true
  }
}


caas {
  thrift {
    host = "user_profile"
    port = "8589"
    timeout_sec = 5
    client_id = "caas-client-from-bi-service"
  }
}


schema {
  thrift {
    host = "ingestion_service"
    port = "8487"
    timeout_sec = 5
    client_id = "ingestion-service-from-bi-service"
  }
}

database {
  mysql {
    url = "jdbc:mysql://mysql:3306?useLegacyDatetimeCode=false&serverTimezone=Asia/Ho_Chi_Minh"
    user = "root"
    password = "root@222"
  }
  clickhouse {
    url = "jdbc:clickhouse://172.20.0.7:9000"
    user = "default"
    password = ""
  }
}

database_schema {
  database {
    name = "bi_service_schema"
  }
  table {
    dashboard {
      name = "dashboard"
      fields = ["id", "name", "main_date_filter", "widgets", "widget_positions", "creator_id"]
    }
    directory {
      name = "directory"
      fields = ["id", "name", "owner_id", "created_date", "parent_id", "is_removed", "dir_type", "dashboard_id"]
    }
    table_relationship {
      name = "table_relationship"
      fields = ["id", "left_table_name", "right_table_name", "left_field", "right_field"]
    }

    permission_token {
      name = "permission_token"
      fields = ["token_id", "creator", "permissions", "created_time"]
    }

    object_sharing_token {
      name = "object_sharing_token"
      fields = ["object_type", "object_id", "token_id"]
    }

  }
}

database_schema_testing {
  database {
    name = "bi_service_schema_test"
  }
  table {
    dashboard {
      name = "dashboard"
      fields = ["id", "name", "main_date_filter", "widgets", "widget_positions", "creator_id"]
    }
    directory {
      name = "directory"
      fields = ["id", "name", "owner_id", "created_date", "parent_id", "is_removed", "dir_type", "dashboard_id"]
    }
    table_relationship {
      name = "table_relationship"
      fields = ["id", "left_table_name", "right_table_name", "left_field", "right_field"]
    }

    permission_token {
      name = "permission_token"
      fields = ["token_id", "creator", "permissions", "created_time"]
    }


    object_sharing_token {
      name = "object_sharing_token"
      fields = ["object_type","object_id", "token_id"]
    }
  }
}

ssdb {
  config {
    host = ssdb
    port = 8888
    timeout_in_ms = 3000
  }
}

fake_data {
  database {
    name = "database_test"
  }
  table {
    customers {
      name = "Customers"
    }
    orders {
      name = "Orders"
    }
    products {
      name = "Products"
    }
  }
}

directory {
  parent_depth = 3
  user_root_dir = "bi-service.user_root_dir"
}


analytics {
   tracking_db_prefix = "analytics_"
   report_analytics_db_prefix = "analytics_report_"

   user_profile_table_name = "profiles"
   event_table_name = "di_user_events"

   report_active_user_collection_tbl = "active_user_collection"
   report_active_user_tbl = "active_user_metrics"

   system_event_names = {
     "di_user_events" : "Events",
     "di_session_created": "Session Created"
     "di_session_end": "Session"
     "di_screen_enter": "Screen Enter"
     "di_screen_exit": "Screen Exit"
     "di_pageview": "PageView"
   }

   activity_hide_events = ["di_session_created","di_screen_enter", "di_screen_exit"]
}