# Nginx configuration

server {
    listen 80;
    server_name explorer.datainsider.co;

    client_max_body_size 100M;
    index index.html;
    error_log  /var/log/nginx/error.log;
    #access_log /var/log/nginx/access.log;
    root /var/www/html/public;

    location / {
   	 proxy_pass http://client:8181;
    }
    location /api/ {
    	proxy_pass  http://server:8058/;
    }
}
