# Nginx configuration

server {
    listen 80;
    server_name static.datainsider.co;

    index index.html;
    error_log  /var/log/nginx/error_static.log;
    access_log /var/log/nginx/access_static.log;
    root /var/www/html/public;

    location / {
	root /var/www/html/public/static;
	sendfile on;
	tcp_nopush on;
	sendfile_max_chunk 1m;
    }
}
