version: '3.7'
services:
  rocket-bi-web:
    image: datainsiderco/rocket-bi-web:main
    container_name: rocket-bi-web
    restart: always
    ports:
      - 5050:8080
    volumes:
      - ./public/config:/app/config

networks:
  default:
    external:
      name: di_network
