export enum DataSourceType {
  MySql = 'MySql',
  MSSql = 'SqlServer',
  Oracle = 'Oracle',
  Redshift = 'Redshift',
  BigQuery = 'BigQuery',
  BigQueryV2 = 'BigQueryV2',
  PostgreSql = 'Postgres',
  GoogleAnalytics = 'GoogleAnalytics',
  GoogleSheet = 'GoogleSheet',
  Others = 'Others',
  GenericJdbc = 'GenericJdbc',
  MongoDB = 'MongoDB',
  Unsupported = 'Unknown',
  JavaScript = 'JavaScript',
  IOS = 'IOS',
  Android = 'Android',
  ReactNative = 'ReactNative',
  Flutter = 'Flutter',
  Shopify = 'Shopify',
  S3 = 'S3'
}
