server {
  http {
    port = ":8580"
  }
  thrift {
    port = ":8589"
  }
  admin {
    port = ":9000"
    disable = false
  }
}

caas {
  restrict_email {
    google = ""
    facebook = ""
  }

  allow_auto_update_profile {
    facebook = false
    u_p = false
    google = false
  }

  org_email {
    google = "^(.+)@datainsider.co"
  }

}

db {

  mysql {
    dbname = caas_dev
    host = mysql
    port = 3306
    username = root
    password = "root@222"
    retry = 5
  }

  oauth {
    pass_secret = "17EIS514KMmQ1g1xxTzq9m86lh7727aF"
    google {
      app_id = "147123631762-p2149desosmqr59un7mbjm2p65k566gh.apps.googleusercontent.com"
    }
    facebook {
      app_secret = ""
    }
  }

  ssdb {
    host = "ssdb"
    port = 8888
    timeout_in_ms = 60000
    username_key = "profiles"
    email_key = "profile.emails"
    phone_number_key = "profile.phones"
  }

}

verification {
  email {
    send_grid {
      api_key = "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",
    }
    sender = "no-reply@dev.datainsider.co"
    direct_verify_host = "http://dev.datainsider.co"
    login_url = "http://dev.datainsider.co/login"
    password_reset_title = "DataInsider Password Changed"
    email_title = "DataInsider Verification Code"
    email_forgot_password_title = "DataInsider Forgot Password Verification Code"
    forgot_email_title = "DataInsider Forgot Password Verification Code"
    forgot_password_message_template = "Password Verification Code: $code"
    code_expire_time_in_second = 1800
    limit_quota = 3
    limit_countdown_in_second = 180
    default_test_code = "123456"
    verification_enabled = true
  }
  phone {
    enabled {
      facebook = false
      u_p = true
      google = false
    }

    message_template = "DataInsider Verification Code: $code"
    forgot_password_message_template = "Password Verification Code: $code"
    code_expire_time_in_second = 180
    limit_quota = 3
    limit_countdown_in_second = 300
    default_test_code = "123456"
  }

}

session {
  authorization = "Authorization"
  domain = ".datainsider.co"
  name = "ssid"
  timeout_in_ms = 31104000000
}


roles {
  10 = "sadmin"
  11 = "admin"
}

