server {
  http {
    port = ":8580"
  }
  thrift {
    port = ":8589"
  }
  admin {
    port = ":9000"
    disable = true
  }
}

caas {
  restrict_email {
    google = ""
    facebook = ""
  }

  allow_auto_update_profile {
    facebook = false
    u_p = false
    google = false
  }
}

db {

  mysql {
    dbname = caas_dev
    host = di-mysql
    port = 3306
    username = root
    password = "di@2020!"
    retry = 5
  }

  ssdb {
    host = "di-ssdb"
    port = 8888
    timeout_in_ms = 60000
    username_key = "profiles"
    email_key = "profile.emails"
    phone_number_key = "profile.phones"
  }

  oauth {
     pass_secret = ""
     google {
       app_id = ""
     }
     facebook {
       app_secret = ""
     }
  }

}

verification {
  email {
    send_grid {
      api_key = "",
    }
    sender = "no-reply@localhost"
    direct_verify_host = "http://localhost"
    login_url = "http://localhost/login"
    password_reset_title = "DataInsider Password Changed"
    email_title = "DataInsider Verification Code"
    email_forgot_password_title = "DataInsider Forgot Password Verification Code"
    forgot_email_title = "DataInsider Forgot Password Verification Code"
    forgot_password_message_template = "Password Verification Code: $code"
    code_expire_time_in_second = 1800
    limit_quota = 3
    limit_countdown_in_second = 180
    default_test_code = "123456"
    verification_enabled = true
  }
  phone {
    enabled {
      facebook = false
      u_p = true
      google = false
    }

    message_template = "DataInsider Verification Code: $code"
    forgot_password_message_template = "Password Verification Code: $code"
    code_expire_time_in_second = 180
    limit_quota = 3
    limit_countdown_in_second = 300
    default_test_code = "123456"
  }

}

session {
  authorization = "Authorization"
  domain = ".localhost"
  name = "ssid"
  timeout_in_ms = 31104000000
}


roles {
}

