# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: SSH to di-oss and redeploy oss version
        run: |
          echo "prepare env"
          sudo apt-get update -qq
          sudo apt-get install -qq git
          which ssh-agent || ( apt-get install -qq openssh-client )
          eval $(ssh-agent -s)
          ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")
          echo "SSH to server, checkout & restart docker"
          ssh sang@34.87.37.29 "cd /data/oss/rocket-bi/ && git checkout master && git pull origin master && ./restart.sh && exit",
          echo done deploy.
