version: '3.7'
services:
  rocket-bi-web:
    image: datainsiderco/rocket-bi-web:latest
    container_name: rocket-bi-web
    restart: always
    ports:
      - 5050:8080
    volumes:
      - ./public/config:/app/config

